spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa  #1.데이터베이스 정보 추가



  jpa:
    #전송 쿼리 확인
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #테이블 생성 후에 data.sql실행
    defer-datasource-initialization: true


  h2:   #2.H2 콘솔 활성화
    console:
      enabled: true
      path: /h2-console  #경로 url

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

logging:
  level:
    org.hibernate.SQL: debug


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <<클라이언트 ID>>
            client-secret: <<비밀번호>>
            scope:
              - email
              - profile






