spring:
  datasource:
    url: jdbc:h2:mem:testdb


  jpa:
    #전송 쿼리 확인
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #테이블 생성 후에 data.sql실행
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console  #경로 url

logging:
  level:
    org.hibernate.SQL: debug





