jwt:
  issuer: ajufresh@gmail.com
  secret-key: test_key

spring:

  jpa:
    #전송 쿼리 확인
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #테이블 생성 후에 data.sql실행
    defer-datasource-initialization: true


  h2:   #2.H2 콘솔 활성화
    console:
      enabled: true
      path: /h2-console  #경로 url

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile


  logging:
    level:
      org.hibernate.SQL: debug






